//! The public API for the Sparse Voxel Octree (SVO) system.
//!
//! This module provides a safe, idiomatic Rust interface for
//! building and managing the SVO data.
//!
//! ## Workflow
//!
//! 1.  Create a `RaytraceWorld` during your app's initialization.
//! 2.  This internally uses an `SvoBuilder` to insert voxel data.
//! 3.  The builder is consumed to create a final, sorted `SvoTree`.
//! 4.  The `RaytraceWorld` then uploads the `SvoTree` data to GPU buffers.
//! 5.  Pass the `ResourceHandle`s for these buffers to your pipelines.

use crate::raytrace::internal::builder::UnsortedStorage;
use crate::raytrace::internal::hashmap::GpuHashmap;
use crate::vulkan::resource::{ResourceHandle, ResourceManager};
use crate::vulkan::util::{self};
use glam::Vec3;
use std::sync::Arc;
use vk_mem as vma;

// --- Internal Implementation ---
// This hides all the messy details from the public API.
mod internal;
mod map;
mod node;
mod world;

// --- Public API ---

/// The final, sorted, GPU-ready Sparse Voxel Octree.
///
/// This struct owns the flat, linear buffer data generated by
/// the `SvoBuilder`. It provides read-only access to the data
/// for uploading to the GPU.
#[derive(Debug)]
pub struct SvoTree {
    /// The final, sorted 65-bit node data.
    node_data: Vec<u64>,
    /// The final, sorted hashmap data.
    hashmap_data: GpuHashmap,

    // --- Tree metadata ---
    pub max_level: u32,
    pub root_min: Vec3,
    pub root_size: f32,
}

impl SvoTree {
    /// Gets the raw node data (the 65-bit bitstream) as bytes for GPU upload.
    pub fn node_data_as_bytes(&self) -> &[u8] {
        if self.node_data.is_empty() {
            return &[];
        }
        // Safely convert the &[u64] slice to &[u8]
        unsafe {
            std::slice::from_raw_parts(
                self.node_data.as_ptr() as *const u8,
                self.node_data.len() * std::mem::size_of::<u64>(),
            )
        }
    }

    /// Gets the raw hashmap table data as bytes for GPU upload.
    ///
    /// **TODO:** The layout of this data depends on the port of the
    /// C++ `GPUHashMap`. This placeholder returns the `std::collections::HashMap`
    /// data, which will not match the GPU's expectation.
    pub fn hashmap_data_as_bytes(&self) -> &[u8] {
        // Placeholder: This is NOT the correct data layout for the GPU.
        // You will need to port the C++ `GPUHashMap` and have this
        // function return its internal `table` slice.
        self.hashmap_data.as_bytes()
    }
}

/// A builder to construct an `SvoTree` from voxel data.
///
/// This struct manages the temporary, unsorted tree state.
/// It is consumed by `build()` to produce the final, sorted `SvoTree`.
pub struct SvoBuilder {
    /// The internal, temporary state used during building.
    storage: internal::builder::UnsortedStorage,

    // --- Tree metadata ---
    max_level: u32,
    root_min: Vec3,
    root_size: f32,
}

impl SvoBuilder {
    /// Corresponds to `Tree64Builder(int max_level, glm::vec3 center)`
    pub fn new(max_level: u32, center: Vec3) -> Self {
        let root_size = internal::builder::get_child_size(max_level) * 4.0;
        let root_min = center - (root_size / 2.0);

        let storage = UnsortedStorage::new(root_min, max_level);

        Self {
            storage,
            max_level,
            root_min,
            root_size,
        }
    }

    /// Inserts a "voxel-box" into the tree.
    /// Corresponds to `Tree64Builder::insert_box`
    pub fn insert_box(&mut self, min_corner: Vec3, max_corner: Vec3) {
        let node_min_corner = self.root_min;
        let node_max_corner = node_min_corner + self.root_size;

        let intersection_min = min_corner.max(node_min_corner);
        let intersection_max = max_corner.min(node_max_corner);

        if intersection_min.x >= intersection_max.x
            || intersection_min.y >= intersection_max.y
            || intersection_min.z >= intersection_max.z
        {
            log::warn!("Box is completely outside the tree bounds.");
            return;
        }

        let mut count = 0;
        const LOWEST_UNIT_VOXEL: f32 = 1.0;

        let mut y = intersection_min.y;
        while y < intersection_max.y {
            let mut z = intersection_min.z;
            while z < intersection_max.z {
                let mut x = intersection_min.x;
                while x < intersection_max.x {
                    count += 1;
                    let pos = Vec3::new(x, y, z);
                    self.storage.insert_recursive(pos);
                    x += LOWEST_UNIT_VOXEL;
                }
                z += LOWEST_UNIT_VOXEL;
            }
            y += LOWEST_UNIT_VOXEL;
        }
        log::info!("Inserted {} voxels for box.", count);
    }

    /// Consumes the builder and performs the expensive sorting
    /// operation, returning the final GPU-ready tree.
    pub fn build(self) -> SvoTree {
        log::info!("Building SVO, sorting nodes...");
        self.storage.print_profile("Unsorted");

        // The sort function consumes the unsorted storage
        // and returns the final, sorted tree components.
        let (sorted_nodes, sorted_hashmap) = internal::builder::sort(self.storage);

        log::info!("SVO build complete.");
        sorted_nodes.print_profile("Sorted");

        SvoTree {
            node_data: sorted_nodes.nodes,
            hashmap_data: sorted_hashmap,
            max_level: self.max_level,
            root_min: self.root_min,
            root_size: self.root_size,
        }
    }
}

/// High-level wrapper that holds the `SvoTree` and its GPU buffers.
/// This replaces the C++ `RaytraceW` singleton and `plugin.cpp` logic.
pub struct RaytraceWorld {
    pub tree: SvoTree,
    pub tree_buffer: Option<ResourceHandle>,
    pub hashmap_buffer: Option<ResourceHandle>,
}

impl RaytraceWorld {
    /// Creates a new world, builds the SVO, and prepares it for the GPU.
    pub fn new() -> Self {
        // Run the bitstream self-test on startup
        internal::bitstream::test_function();

        // C++: ray_world.tree = Tree64Builder(SHADER_MAX_TREE_LEVEL, {0, 0, 0});
        // SHADER_MAX_TREE_LEVEL from `rayshared.inl` is assumed to be 4.
        const SHADER_MAX_TREE_LEVEL: u32 = 4;

        // 1. Use the SvoBuilder
        let mut builder = SvoBuilder::new(SHADER_MAX_TREE_LEVEL, Vec3::ZERO);

        // 2. Insert data (replaces loading "assets/castle.vox")
        // We use the test data from your plugin.cpp
        log::info!("Inserting test box into octree...");
        // C++: ray_world.tree.insert_box(glm::vec3(0, 0, 0), glm::vec3(4, 4, 4));
        builder.insert_box(Vec3::new(0.0, 0.0, 0.0), Vec3::new(4.0, 4.0, 4.0));

        // 3. Build the tree (consumes the builder)
        let tree = builder.build();

        Self {
            tree,
            tree_buffer: None,
            hashmap_buffer: None,
        }
    }

    /// Call this to create the GPU buffers for the tree.
    /// This should be called once during your `App::initialize`.
    pub fn create_gpu_buffers(&mut self, resource_manager: &Arc<ResourceManager>) {
        // --- 1. Create Node Buffer ---
        let node_data_bytes = self.tree.node_data_as_bytes();
        if node_data_bytes.is_empty() {
            log::warn!("Octree node data is empty, skipping buffer creation.");
            return;
        }

        log::info!(
            "Creating GPU octree node buffer of {} bytes",
            node_data_bytes.len()
        );

        let node_buffer_info = util::helper::storage_buffer_info(
            node_data_bytes.len() as u64,
            vma::MemoryUsage::AutoPreferDevice,
        );

        // TODO: This buffer needs to be filled with `node_data_bytes`.
        // You will need an upload function (e.g., using a staging buffer)
        // to copy the data to this device-local buffer.
        let tree_buffer_handle =
            resource_manager.create_buffer("Octree Node Buffer".to_string(), node_buffer_info);
        self.tree_buffer = Some(tree_buffer_handle);

        // --- 2. Create Hashmap Buffer ---
        let hashmap_data_bytes = self.tree.hashmap_data_as_bytes();
        if hashmap_data_bytes.is_empty() {
            log::warn!("Octree hashmap data is empty, skipping buffer creation.");
            return;
        }

        // ... (Similar logic to create and upload the hashmap buffer) ...
        // let hashmap_buffer_info = ...
        // let hashmap_buffer_handle = resource_manager.create_buffer(...)
        // self.hashmap_buffer = Some(hashmap_buffer_handle);
    }
}
